config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/products')

  resources :products do
    get 'compare', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, length: { minimum: 1, maximum: 50 } # 8
  validates :description, presence: true, length: { minimum: 1, maximum: 800 } # 20
  validates :price, presence: true, length: { minimum: 2, maximum: 8 }
  validates :ram, presence: true, length: { minimum: 1, maximum: 6 }
  validates :cpu, presence: true, length: { minimum: 6, maximum: 20 }
  validates :gpu, presence: true, length: { minimum: 10, maximum: 20 }
  validates :picture, presence: true, file_size: { less_than: 1.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :compare, :get_compare_products

  # Places per page
  PLACES_PER_PAGE = 9

  # GET /products or /products.json
  def index
    @products = Product.paginate(page: params[:page],
                                                      per_page: PLACES_PER_PAGE)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to @product, notice: "Product was successfully created."
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to @product, notice: "Product was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @product.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html do
        redirect_to products_url,
        notice: "Product was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def compare
    @compare_products = Product.where(id: @products_id_array)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :ram, :cpu,
                                                                :gpu, :picture)
    end

    def get_compare_products
      @cookie = cookies[:compareItems]
      @products_id_array =  if @cookie then JSON.parse(@cookie) end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikeShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible position-absolute start-50 fade show"
                                                                  role='alert'>
        <button type="button" class='btn-close' data-bs-dismiss='alert'></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                                              crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_compare_item.html.erb
<div class="col-3 border-end">
  <p class="fs-5"><%= c_product.name %></p>
  <hr>
  <p><%= c_product.ram %></p>
  <hr>
  <p><%= c_product.cpu %></p>
  <hr>
  <p><%= c_product.gpu %></p>
  <hr>
  <p><%= c_product.price %></p>
  <hr>
</div>

app/views/products/_form.html.erb
<div class="container new-product-form">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= form_with(model: product) do |f| %>
        <div class="border border-secondary rounded-3 p-4 mt-4">
          <div class="mb-3 position-relative">
            <% if product.errors[:name] %>
              <%= f.label :name, class: 'form-label' %>
              <%= f.text_field :name, class: 'form-control',
                                                    placeholder: 'Product name',
                                                    alt:  'Product name' %>
            <% end %>
            <p class='error-message'><%= product.errors[:name].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <%= f.label :description, class: 'form-label' %>
            <% if product.errors[:description] %>
              <%= f.text_area :description, class: 'form-control',
                                        placeholder: 'Something about place..',
                                              alt: 'Description', size: '80' %>
            <% end %>
            <p class='error-message'><%= product.errors[:description].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <% if product.errors[:ram] %>
              <%= f.label :ram, class: 'form-label' %>
              <%= f.text_field :ram, class: 'form-control',
                                                       placeholder: 'RAM value',
                                                       alt: 'RAM value' %>
            <% end %>
            <p class='error-message'><%= product.errors[:ram].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <% if product.errors[:cpu] %>
              <%= f.label :cpu, class: 'form-label' %>
              <%= f.text_field :cpu, class: 'form-control',
                                                      placeholder: 'CPU model',
                                                      alt: 'CPU model' %>
            <% end %>
            <p class='error-message'><%= product.errors[:cpu].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <% if product.errors[:gpu] %>
              <%= f.label :gpu, class: 'form-label' %>
              <%= f.text_field :gpu, class: 'form-control',
                                                      placeholder: 'GPU model',
                                                      alt: 'GPU model' %>
            <% end %>
            <p class='error-message'><%= product.errors[:gpu].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <%= f.label :picture, class: 'form-label' %>
            <% if product.errors[:picture] %>
              <%= f.file_field :picture, class: 'form-control',
                    placeholder: 'Select you file', alt: 'picture uploader' %>
            <% end %>
            <p class='error-message'><%= product.errors[:picture].first %></p>
          </div>
          <div class="mb-3 position-relative">
            <%= f.label :price, class: 'form-label' %>
            <% if product.errors[:price] %>
              <%= f.text_field :price, class: 'form-control',
                                        placeholder: '0.00', alt: 'price' %>
            <% end %>
            <p class='error-message'><%= product.errors[:price].first %></p>
          </div>
        </div>
        <div class="m-3 text-center w-4">
          <%= f.submit 'Create', class: 'btn btn-primary m-2 p-2 px-5' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col-md d-flex mb-3 justify-content-center">
  <div class="card" style="width: 18rem;">
    <%= image_tag product.picture.thumb.url, class: 'card-img-top', alt: 'image' %>
    <div class="card-body">
      <h5 class="card-title"><%= product.name %></h5>
      <p class="card-text mb-5"><%= product.description.truncate(125) %></p>
      <div class="position-absolute bottom-0 m-3">
        <%= link_to '$' + product.price.to_s, product,
                                class: 'btn btn-primary text-white price-btn' %>
        <%= link_to 'Destroy', product, class: 'link-danger bg-white mx-3',
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %>
        <span data-attribute-id='<%= product.id %>' class='compare_button'>
          <%= image_tag 'weigher.png', width: '30px' %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/products/compare.html.erb
<div class="compare-page">
  <%= link_to 'Back', products_path, class: 'btn btn-success mt-5 rounded-pill rounded-start text-white' %>

  <div class="container overflow-auto">
    <div class="row">
      <% if @compare_products.count < 2 && @compare_products.present? %>
        <div class="col-12">
          <p class='fs-3 text-center mt-5'>Please select more than one product</p>
        </div>
      <% elsif @compare_products.present? %>
        <div class="container text-center">
          <h1>Compare your items:</h1>
        </div>
        <div class="row flex-row flex-nowrap">
          <div class="col-3"></div>
          <% @compare_products.each do |product| %>
              <div class="col-3">
                <p><%= image_tag product.picture.url, class: 'card-img-top', alt: 'image' %></p>
              </div>
          <% end %>
        </div>
        <div class="row flex-row flex-nowrap">
          <div class="col-3 border-end">
            <p class="fs-6">Name:</p>
            <hr>
            <p class="fs-6">RAM:</p>
            <hr>
            <p class="fs-6">CPU:</p>
            <hr>
            <p class="fs-6">GPU:</p>
            <hr>
            <p class="fs-6">Price:</p>
            <hr>
          </div>
          <% @compare_products.each do |c_product| %>
            <%= render 'compare_item', c_product: c_product %>
          <% end %>
        </div>
      <% else %>
      <div class="col-12">
        <p class='fs-3 text-center mt-5'>Sorry, but your list is empty</p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-lg-3"></div>
    <div class="col-lg-9 col-12">
      <h1>Products</h1>
    </div>
  </div>
  <div class="row mt-5 justify-content-center">
    <div class="col-md">
      <div class="row">
        <div class="col-12 text-center mb-5">
          <%= link_to 'New Product', new_product_path,
                                              class: 'btn btn-success text-white' %>
          <br><br>
          <%= link_to 'Compare', compare_products_path,
                                          id: 'link_to_compare',
                                          class: 'btn btn-success text-white' %>
        </div>
      </div>
    </div>
    <div class="col-9">
      <div class="row">
        <% @products.each do |product| %>
          <%= render product %>
        <% end %>
      </div>
      <div class="pagination justify-content-center">
        <%= will_paginate @products,
                    renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'products/index' %>

app/views/products/new.html.erb
<%= link_to 'Back', products_path, class: 'btn btn-success mt-5 rounded-pill rounded-start text-white' %>
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>New Product</h1>
    </div>
  </div>
</div>
<%= render 'form', product: @product %>

<%= javascript_pack_tag 'products/new' %>
<%= javascript_pack_tag 'shared/validations' %>

app/views/products/show.html.erb
<%= link_to 'Back', products_path, class: 'btn btn-success mt-5 rounded-pill ' +
                                                  'rounded-start text-white' %>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <%= image_tag @product.picture.url, width: '100%', alt: 'image' %>
    </div>
    <div class="col-lg-6">
      <h1><%= @product.name %></h1>
      <hr>
      <p class='fs-6'><%= @product.description %></p>
      <br>
      <p class="fs-5">Characteristics:</p><br>
      <p class="fs-6">RAM: <%= @product.ram %></p>
      <hr>
      <p class="fs-6">CPU: <%= @product.cpu %></p>
      <hr>
      <p class="fs-6">GPU: <%= @product.gpu %></p>
      <hr><br>
      <div class="row mb-3">
        <div class="col-6">
          <p class='fs-3 mt-2 text-center'>$<%= @product.price %></p>
        </div>
        <div class="col-6">
          <span><%= link_to 'Edit', edit_product_path(@product),
                        class: 'btn btn-success fs-4 text-white me-3' %></span>
          <span data-attribute-id='<%= @product.id %>' class='compare_button'>
            <%= image_tag 'weigher.png', width: '30px' %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'products/show' %>